services:
  collector:
    image: anime-datacollector:latest
    build: .
    depends_on:
      - db
    volumes:
      - ./code:/code
  db:
    image: influxdb:2.5.1
    ports:
      - "8086:8086"
    volumes:
      - D:/datasets/MAL_datacollection/db_data:/var/lib/influxdb2
  grafana:
    image: grafana/grafana
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - D:/datasets/MAL_datacollection/grafana-storage:/var/lib/grafana