services:
  collector:
    image: anime-datacollector:latest
    build: .
    depends_on:
      - db
    volumes:
      - ./secrets.sh:/home/secrets.sh
  db:
    image: influxdb:2.5.1
    ports:
      - "8086:8086"
    volumes:
      - ./db_data:/var/lib/influxdb2
  grafana:
    image: grafana/grafana
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana